// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocal.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Protocal_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Protocal_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3015000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3015007 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Protocal_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Protocal_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Protocal_2eproto;
::PROTOBUF_NAMESPACE_ID::Metadata descriptor_table_Protocal_2eproto_metadata_getter(int index);
class PBindName;
struct PBindNameDefaultTypeInternal;
extern PBindNameDefaultTypeInternal _PBindName_default_instance_;
class PChat;
struct PChatDefaultTypeInternal;
extern PChatDefaultTypeInternal _PChat_default_instance_;
class PRoomInformation;
struct PRoomInformationDefaultTypeInternal;
extern PRoomInformationDefaultTypeInternal _PRoomInformation_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::PBindName* Arena::CreateMaybeMessage<::PBindName>(Arena*);
template<> ::PChat* Arena::CreateMaybeMessage<::PChat>(Arena*);
template<> ::PRoomInformation* Arena::CreateMaybeMessage<::PRoomInformation>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class PBindName PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PBindName) */ {
 public:
  inline PBindName() : PBindName(nullptr) {}
  virtual ~PBindName();
  explicit constexpr PBindName(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PBindName(const PBindName& from);
  PBindName(PBindName&& from) noexcept
    : PBindName() {
    *this = ::std::move(from);
  }

  inline PBindName& operator=(const PBindName& from) {
    CopyFrom(from);
    return *this;
  }
  inline PBindName& operator=(PBindName&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PBindName& default_instance() {
    return *internal_default_instance();
  }
  static inline const PBindName* internal_default_instance() {
    return reinterpret_cast<const PBindName*>(
               &_PBindName_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PBindName& a, PBindName& b) {
    a.Swap(&b);
  }
  inline void Swap(PBindName* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PBindName* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PBindName* New() const final {
    return CreateMaybeMessage<PBindName>(nullptr);
  }

  PBindName* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PBindName>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PBindName& from);
  void MergeFrom(const PBindName& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PBindName* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PBindName";
  }
  protected:
  explicit PBindName(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_Protocal_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
  };
  // string name = 1;
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // @@protoc_insertion_point(class_scope:PBindName)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Protocal_2eproto;
};
// -------------------------------------------------------------------

class PChat PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PChat) */ {
 public:
  inline PChat() : PChat(nullptr) {}
  virtual ~PChat();
  explicit constexpr PChat(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PChat(const PChat& from);
  PChat(PChat&& from) noexcept
    : PChat() {
    *this = ::std::move(from);
  }

  inline PChat& operator=(const PChat& from) {
    CopyFrom(from);
    return *this;
  }
  inline PChat& operator=(PChat&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PChat& default_instance() {
    return *internal_default_instance();
  }
  static inline const PChat* internal_default_instance() {
    return reinterpret_cast<const PChat*>(
               &_PChat_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(PChat& a, PChat& b) {
    a.Swap(&b);
  }
  inline void Swap(PChat* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PChat* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PChat* New() const final {
    return CreateMaybeMessage<PChat>(nullptr);
  }

  PChat* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PChat>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PChat& from);
  void MergeFrom(const PChat& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PChat* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PChat";
  }
  protected:
  explicit PChat(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_Protocal_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kInformationFieldNumber = 1,
  };
  // string information = 1;
  void clear_information();
  const std::string& information() const;
  void set_information(const std::string& value);
  void set_information(std::string&& value);
  void set_information(const char* value);
  void set_information(const char* value, size_t size);
  std::string* mutable_information();
  std::string* release_information();
  void set_allocated_information(std::string* information);
  private:
  const std::string& _internal_information() const;
  void _internal_set_information(const std::string& value);
  std::string* _internal_mutable_information();
  public:

  // @@protoc_insertion_point(class_scope:PChat)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr information_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Protocal_2eproto;
};
// -------------------------------------------------------------------

class PRoomInformation PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PRoomInformation) */ {
 public:
  inline PRoomInformation() : PRoomInformation(nullptr) {}
  virtual ~PRoomInformation();
  explicit constexpr PRoomInformation(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PRoomInformation(const PRoomInformation& from);
  PRoomInformation(PRoomInformation&& from) noexcept
    : PRoomInformation() {
    *this = ::std::move(from);
  }

  inline PRoomInformation& operator=(const PRoomInformation& from) {
    CopyFrom(from);
    return *this;
  }
  inline PRoomInformation& operator=(PRoomInformation&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PRoomInformation& default_instance() {
    return *internal_default_instance();
  }
  static inline const PRoomInformation* internal_default_instance() {
    return reinterpret_cast<const PRoomInformation*>(
               &_PRoomInformation_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(PRoomInformation& a, PRoomInformation& b) {
    a.Swap(&b);
  }
  inline void Swap(PRoomInformation* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PRoomInformation* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PRoomInformation* New() const final {
    return CreateMaybeMessage<PRoomInformation>(nullptr);
  }

  PRoomInformation* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PRoomInformation>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PRoomInformation& from);
  void MergeFrom(const PRoomInformation& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PRoomInformation* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PRoomInformation";
  }
  protected:
  explicit PRoomInformation(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_Protocal_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
    kInfomationFieldNumber = 2,
  };
  // string name = 1;
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // string infomation = 2;
  void clear_infomation();
  const std::string& infomation() const;
  void set_infomation(const std::string& value);
  void set_infomation(std::string&& value);
  void set_infomation(const char* value);
  void set_infomation(const char* value, size_t size);
  std::string* mutable_infomation();
  std::string* release_infomation();
  void set_allocated_infomation(std::string* infomation);
  private:
  const std::string& _internal_infomation() const;
  void _internal_set_infomation(const std::string& value);
  std::string* _internal_mutable_infomation();
  public:

  // @@protoc_insertion_point(class_scope:PRoomInformation)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr infomation_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Protocal_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PBindName

// string name = 1;
inline void PBindName::clear_name() {
  name_.ClearToEmpty();
}
inline const std::string& PBindName::name() const {
  // @@protoc_insertion_point(field_get:PBindName.name)
  return _internal_name();
}
inline void PBindName::set_name(const std::string& value) {
  _internal_set_name(value);
  // @@protoc_insertion_point(field_set:PBindName.name)
}
inline std::string* PBindName::mutable_name() {
  // @@protoc_insertion_point(field_mutable:PBindName.name)
  return _internal_mutable_name();
}
inline const std::string& PBindName::_internal_name() const {
  return name_.Get();
}
inline void PBindName::_internal_set_name(const std::string& value) {
  
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void PBindName::set_name(std::string&& value) {
  
  name_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:PBindName.name)
}
inline void PBindName::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:PBindName.name)
}
inline void PBindName::set_name(const char* value,
    size_t size) {
  
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:PBindName.name)
}
inline std::string* PBindName::_internal_mutable_name() {
  
  return name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* PBindName::release_name() {
  // @@protoc_insertion_point(field_release:PBindName.name)
  return name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PBindName::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:PBindName.name)
}

// -------------------------------------------------------------------

// PChat

// string information = 1;
inline void PChat::clear_information() {
  information_.ClearToEmpty();
}
inline const std::string& PChat::information() const {
  // @@protoc_insertion_point(field_get:PChat.information)
  return _internal_information();
}
inline void PChat::set_information(const std::string& value) {
  _internal_set_information(value);
  // @@protoc_insertion_point(field_set:PChat.information)
}
inline std::string* PChat::mutable_information() {
  // @@protoc_insertion_point(field_mutable:PChat.information)
  return _internal_mutable_information();
}
inline const std::string& PChat::_internal_information() const {
  return information_.Get();
}
inline void PChat::_internal_set_information(const std::string& value) {
  
  information_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void PChat::set_information(std::string&& value) {
  
  information_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:PChat.information)
}
inline void PChat::set_information(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  information_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:PChat.information)
}
inline void PChat::set_information(const char* value,
    size_t size) {
  
  information_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:PChat.information)
}
inline std::string* PChat::_internal_mutable_information() {
  
  return information_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* PChat::release_information() {
  // @@protoc_insertion_point(field_release:PChat.information)
  return information_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PChat::set_allocated_information(std::string* information) {
  if (information != nullptr) {
    
  } else {
    
  }
  information_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), information,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:PChat.information)
}

// -------------------------------------------------------------------

// PRoomInformation

// string name = 1;
inline void PRoomInformation::clear_name() {
  name_.ClearToEmpty();
}
inline const std::string& PRoomInformation::name() const {
  // @@protoc_insertion_point(field_get:PRoomInformation.name)
  return _internal_name();
}
inline void PRoomInformation::set_name(const std::string& value) {
  _internal_set_name(value);
  // @@protoc_insertion_point(field_set:PRoomInformation.name)
}
inline std::string* PRoomInformation::mutable_name() {
  // @@protoc_insertion_point(field_mutable:PRoomInformation.name)
  return _internal_mutable_name();
}
inline const std::string& PRoomInformation::_internal_name() const {
  return name_.Get();
}
inline void PRoomInformation::_internal_set_name(const std::string& value) {
  
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void PRoomInformation::set_name(std::string&& value) {
  
  name_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:PRoomInformation.name)
}
inline void PRoomInformation::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:PRoomInformation.name)
}
inline void PRoomInformation::set_name(const char* value,
    size_t size) {
  
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:PRoomInformation.name)
}
inline std::string* PRoomInformation::_internal_mutable_name() {
  
  return name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* PRoomInformation::release_name() {
  // @@protoc_insertion_point(field_release:PRoomInformation.name)
  return name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PRoomInformation::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:PRoomInformation.name)
}

// string infomation = 2;
inline void PRoomInformation::clear_infomation() {
  infomation_.ClearToEmpty();
}
inline const std::string& PRoomInformation::infomation() const {
  // @@protoc_insertion_point(field_get:PRoomInformation.infomation)
  return _internal_infomation();
}
inline void PRoomInformation::set_infomation(const std::string& value) {
  _internal_set_infomation(value);
  // @@protoc_insertion_point(field_set:PRoomInformation.infomation)
}
inline std::string* PRoomInformation::mutable_infomation() {
  // @@protoc_insertion_point(field_mutable:PRoomInformation.infomation)
  return _internal_mutable_infomation();
}
inline const std::string& PRoomInformation::_internal_infomation() const {
  return infomation_.Get();
}
inline void PRoomInformation::_internal_set_infomation(const std::string& value) {
  
  infomation_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void PRoomInformation::set_infomation(std::string&& value) {
  
  infomation_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:PRoomInformation.infomation)
}
inline void PRoomInformation::set_infomation(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  infomation_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:PRoomInformation.infomation)
}
inline void PRoomInformation::set_infomation(const char* value,
    size_t size) {
  
  infomation_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:PRoomInformation.infomation)
}
inline std::string* PRoomInformation::_internal_mutable_infomation() {
  
  return infomation_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* PRoomInformation::release_infomation() {
  // @@protoc_insertion_point(field_release:PRoomInformation.infomation)
  return infomation_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PRoomInformation::set_allocated_infomation(std::string* infomation) {
  if (infomation != nullptr) {
    
  } else {
    
  }
  infomation_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), infomation,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:PRoomInformation.infomation)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Protocal_2eproto
